const Action = {

    LOAD_EXERCISES:"LOAD_EXERCISES",
    ADD_EXERCISE:"ADD_EXERCISE",
    REMOVE_EXERCISE:"REMOVE_EXERCISE",
    EDIT_EXERCISE:"EDIT_EXERCISE",
    ADD_BODYPART:"ADD_BODYPART",
    REMOVE_BODYPART:"REMOVE_BODYPART"
}

const WorkoutListActions = {
    LOAD_WORKOUTS:"LOAD_WORKOUTS",
    ADD_EXERCISE:"ADD_EXERCISE",
    REMOVE_EXERCISE:"REMOVE_EXERCISE",
    REORDER_EXERCISE:"REORDER_EXERCISE"
}

export default Action;
export {WorkoutListActions}